### ISSUE TITLE
IE8 Fallback?

### ISSUE THREAD

**Issue by dagjomar** [hiasinho/Leaflet.vector-markers#2]
I tried to view the demo on IE8, but it doesn't seem to render the SVG. 

Any way to implement fallback to VML rendering?

**Comment by seadour** [comment]
You might want to use a separate feature-detection library such as Modernizr (https://modernizr.com/) to detect whether or not the browser supports SVG and load raster icons as a fallback for browsers that don't support SVG.

    var redMarker;

    if (Modernizr.svg) {
        redMarker = L.VectorMarkers.icon({
           icon: 'coffee',
           markerColor: 'red'
        });
    } else {
        redMarker = L.icon({
          iconUrl: 'red-coffee.png',
        });
    }

    L.marker([lat,long], {icon: redMarker}).addTo(map);

On the Modernizr download page (https://modernizr.com/download?setclasses), you can specify which features you want and only download the source code for those features to keep your javascript lightweight.

I think a raster fallback for IE8 would be better than a VML fallback since VML is no longer supported by Microsoft as of IE10. (https://msdn.microsoft.com/en-us/library/hh801223(v=vs.85).aspx)  I know it will probably make your map look worse and/or remove some functionality, but at least it will still be functional for those still using older browsers.

**Comment by hiasinho** [comment]
I will close this, as I don't want to support IE8. Sorry.
